<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ClipboardHistoryManager</AssemblyName>
    <RootNamespace>ClipboardHistoryManager</RootNamespace>
    <LangVersion>latest</LangVersion>
    <ApplicationTitle>クリップボード履歴マネージャー</ApplicationTitle>
    <Version>1.0.0</Version>
    <Company>おのソフト</Company>
    <Product>クリップボード履歴マネージャー</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OnoSoft.Shared\OnoSoft.Shared.csproj" />
  </ItemGroup>

</Project>
