<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OnoSoft.Shared</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Company>おのソフト</Company>
    <Product>OnoSoft Shared Library</Product>
  </PropertyGroup>

</Project>
